apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snapshots-quota
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snapshots-quota.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
